name: Bump version
on:
  push:
    branches: [master]

jobs:
  build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@v1 # Don't use @master or @v1 unless you're happy to test the latest version
        env:
          GITHUB_TOKEN: ${{ secrets.GIANT_PAT }} # if you don't want to set write permissions use a PAT token
          WITH_V: false
          PRERELEASE: false
          DEFAULT_BUMP: patch
