name: Linter y tests

on:
  pull_request:
    branches:
      - master
    types: [opened, reopened, synchronize]

jobs:
  build-test-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Determine tag"
        run: 'echo "RELEASE_TAG=0.0.1" >> $GITHUB_ENV'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        id: build-and-push
        with:
          push: true
          tags: dcristobal/port-scan-exporter-app:latest,dcristobal/port-scan-exporter-app:${{ env.RELEASE_TAG }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "dcristobal/port-scan-exporter-app:${{ env.RELEASE_TAG }}"
          format: "table"
          exit-code: "1"
          ignore-unfixed: true
          vuln-type: "os,library"
          severity: "CRITICAL"

  chart-test:
    runs-on: ubuntu-latest
    needs: [build-test-image]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Determine tag"
        run: 'echo "RELEASE_TAG=0.0.1" >> $GITHUB_ENV'

      - name: Install yq
        run: sudo pip install yq

      - name: Update appVersion in the YAML file
        run: |
          yq -Y --in-place '.appVersion = "${{ env.RELEASE_TAG }}"' charts/port-scan-exporter/Chart.yaml

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.1

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          check-latest: true

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.7.0

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --target-branch ${{ github.event.repository.default_branch }}
